main: com.evilmidget38.structuresaver.StructureSaver
version: 0.1
name: StructureSaver
author: evilmidget38
commands:
  save-structures:
    permission: structuresaver.save
    usage: /<command> [worldname]
    description: Saves all structures in the given world, or in all worlds.